server:
  port: 8785

kafka:
  bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
  consumer:
    topic: notification
    group: notification-event-group
    auto-offset-reset: earliest

spring:
  mail:
    host: ${MAIL_HOST:localhost} #For demo purposes you can use fakeSMTP
    port: ${MAIL_PORT:25} # SMTP server port
    username: ${MAIL_USERNAME:}# Login used for authentication
    password: ${MAIL_PASSWORD:}# Password for the given login
    protocol: ${MAIL_PROTOCOL:smtp}
    defaultEncoding: UTF-8 # Default message encoding
  #mongodb
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: notifications

notification:
  sender:
   email: no-reply@urban-ms-ecosystem.com
  template:
    mapping:
      CREATE_USER: verifyEmailTemplate, welcomeTemplate
      UPDATE_USER: userDataUpdatedTemplate
      EMAIL_CHANGE: emailUpdatedTemplate
  subject:
    mapping:
      verifyEmailTemplate: Email Verification
      welcomeTemplate: Welcome Aboard!
      userDataUpdatedTemplate: Your Account Info Has changed
      emailUpdatedTemplate: Email Account Has Changed
