server:
  port: 9090

endpoints:
  info:
    enabled: true
info:
  app:
    name: auth-server
    description: Oauth2 w/JWT - Authentication Server
    version: @project.version@

spring:
  datasource:
    url: jdbc:h2:~/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9797;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: test123

  h2:
    console:
      enabled: true

security:
  oauth2:
    resource:
      id: auth_server
access_token:
  validity_period: 3600
refresh_token:
  validity_period: 10000

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
