server:
  port: 8080

zuul:
  prefix: /api
  routes:
    auth:
      path: /auth/**
      add-proxy-headers: true
      sensitiveHeaders: #This is required to fw sensitive headers as Authorization
      serviceId: auth-server
    api:
      path: /resources/**
      add-proxy-headers: true
      sensitiveHeaders:
      serviceId: urban-service
  host:
    socket-timeout-millis: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

endpoints:
  routes:
    sensitive: false
  info:
    enabled: true
info:
  app:
    name: api-gateway
    description: API Gateway
    version: @project.version@