zuul:
  routes:
    auth:
      path: /api/auth/**
      serviceId: auth-server
    api:
      path: /api/resources/**
      serviceId: urban-service

ribbon:
  eureka:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true

#Will start the gateway server @8080
server:
  port: 8080