zuul:
  routes:
    auth:
      path: /api/auth/**
      serviceId: auth-server
    api:
      path: /api/resources/**
      serviceId: urban-service

ribbon:
  eureka:
    enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    fetchRegistry: true
  instance:
    preferIpAddress: true

#Will start the gateway server @8080
server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: api-gateway