spring:
  profiles:
    active: dev
  application:
    name: api-gateway

endpoints:
  info:
    enabled: true
info:
  app:
    name: api-gateway
    description: API Gateway
    version: @project.version@

zuul:
  routes:
    auth:
      path: /api/auth/**
      add-proxy-headers: true
      serviceId: auth-server
    api:
      path: /api/resources/**
      add-proxy-headers: true
      serviceId: urban-service

ribbon:
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
  instance:
    preferIpAddress: true

#Will start the gateway server @8080
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultzone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 10

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000