server:
  port: 8090
auth:
  server:
    url: ${OAUTH_URI:http://localhost:9090/oauth/check_token}
    clientId: trusted-app
    clientsecret: secret
    resourceId: urban-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

info:
  app:
    name: urban-service
    description: Urban Service API - Resource Server
    version: @project.version@