server:
  port: 9595
auth:
  server:
    url: ${OAUTH_URI:http://localhost:9090/oauth/check_token}
    clientId: trusted-app
    clientsecret: secret
    resourceId: urban-service
spring:
  datasource:
    url: jdbc:h2:~/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9797;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

info:
  app:
    name: user-service
    description: User Service API
    version: @project.version@