server:
  port: 9595
auth:
  server:
    url: ${OAUTH_URI:http://localhost:9090/oauth}
    uri:
      check: ${OAUTH_CHECK:/check_token}
      token: ${OAUTH_TOKEN:/token}
    clientId: trusted-app
    clientsecret: secret
    resourceId: urban-service
spring:
  datasource:
    url: jdbc:h2:~/data/test;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9797;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: test123
  h2:
    console:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      topic: ${KAFKA_TOPIC:notifications}
      retries: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

info:
  app:
    name: user-service
    description: User Service API
    version: @project.version@

activate:
  endpoint:
    url: http://localhost:9595/users/verify?code=%s # Endpoint to activate the user.