server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0